language: php

php:
  - 7.1
  - 7.2

sudo: false

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 travis_wait composer install --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
